name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Allow repository check out with actions/checkout@v2
        uses: actions/checkout@v2
      - name: Setting up Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Making Gradle wrapper file executable (chmod +x gradlew)
        run: chmod +x gradlew
      - name: Publish package
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}